rest_client:
  type: config_object
  mapping:
    oauth_base_uri:
      type: string
      label: "The OAuth base URI."
    oauth_username:
      type: string
      label: "The OAuth username."
    oauth_password:
      type: string
      label: "The OAuth password."
    oauth_token:
      type: string
      label: "The OAuth token that accompanies the password."
    oauth_client_id:
      type: string
      label: "The OAuth client Id."
    oauth_client_secret:
      type: string
      label: "The OAuth client secret."
    api_version:
      type: string
      label: "The API version."